# ===============================================================
# SERVER CONFIGURATION
# ===============================================================
server.host: localhost
server.port: 8080

# ===============================================================
# LOGGING CONFIGURATION
# ===============================================================
log.level: ERROR
log.profile: console
