name: jeafio/http

on:
  push:
    branches: [ master ]
    paths: 'packages/jeafio-http/**'
  pull_request:
    branches: [ master ]
    paths: 'packages/jeafio-http/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn run lint
      working-directory: ./packages/jeafio-http
    - run: yarn run test
      working-directory: ./packages/jeafio-http
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./packages/jeafio-http/coverage/coverage-final.json
        flags: jeafio/http
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
