name: jeafio-profile

on:
  push:
    branches: [ master ]
    paths: 'packages/jeafio-profile/**'
  pull_request:
    branches: [ master ]
    paths: 'packages/jeafio-profile/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn run lint
      working-directory: ./packages/jeafio-profile
    - run: yarn run test
      working-directory: ./packages/jeafio-profile
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./packages/jeafio-profile/coverage
        flags: jeafio-profile